DROP USER POLICY_ADMIN CASCADE;
CREATE USER "POLICY_ADMIN" IDENTIFIED BY "POLICY_ADMIN";
GRANT CONNECT, RESOURCE, SELECT_CATALOG_ROLE TO POLICY_ADMIN;

DROP USER DB_ADMIN CASCADE;
CREATE USER "DB_ADMIN" IDENTIFIED BY "DB_ADMIN";
GRANT CONNECT, RESOURCE, SELECT_CATALOG_ROLE TO DB_ADMIN;
GRANT UNLIMITED TABLESPACE TO DB_ADMIN;

CREATE USER "BANK_PRESIDENT1" IDENTIFIED BY "BP";
CREATE USER "BANK_MANAGER1" IDENTIFIED BY "BM";
CREATE USER "BANK_SUPERVISOR1" IDENTIFIED BY "BS";
CREATE USER "BANK_TELLER1" IDENTIFIED BY "BT";
CREATE USER "BANK_PRESIDENT_NO_COMPARTMENT" IDENTIFIED BY "BP";
CREATE USER "BANK_MANAGER_LOW_GROUP" IDENTIFIED BY "BM";
CREATE USER "PROSECUTOR" IDENTIFIED BY "PROSECUTOR";
CREATE USER "DOC1" IDENTIFIED BY "DOC1";

GRANT CREATE SESSION TO "BANK_PRESIDENT1", "BANK_MANAGER1", "BANK_SUPERVISOR1", "BANK_TELLER1", "BANK_PRESIDENT_NO_COMPARTMENT", "BANK_MANAGER_LOW_GROUP", "PROSECUTOR", "DOC1";

GRANT CONNECT TO "BANK_PRESIDENT1", "BANK_MANAGER1", "BANK_SUPERVISOR1", "BANK_TELLER1", "BANK_PRESIDENT_NO_COMPARTMENT", "BANK_MANAGER_LOW_GROUP", "PROSECUTOR", "DOC1";

GRANT SELECT, UPDATE, DELETE, INSERT ON DB_ADMIN.BANK_RECORDS TO PUBLIC;