GRANT EXECUTE ON sa_components TO DB_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON sa_user_admin TO DB_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON sa_user_admin TO DB_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON sa_label_admin TO DB_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON sa_policy_admin TO DB_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON sa_audit_admin  TO DB_ADMIN WITH GRANT OPTION;

GRANT LBAC_DBA TO DB_ADMIN;
GRANT EXECUTE ON sa_sysdba TO DB_ADMIN;
GRANT EXECUTE ON to_lbac_data_label TO DB_ADMIN;