EXECUTE SA_COMPONENTS.CREATE_LEVEL('OLS_POLICY',4,'HS','HIGHLY_SENSITIVE');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('OLS_POLICY',3,'S','SENSITIVE');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('OLS_POLICY',2,'C','CONFIDENTIAL');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('OLS_POLICY',1,'U','UNCLASSIFIED');

EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('OLS_POLICY',1,'BK','BANK');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('OLS_POLICY',2,'PO','POLICE');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('OLS_POLICY',3,'HP','HOSPITAL');

EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_POLICY',5,'PRO','PROSECUTOR');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_POLICY',4,'BP','BANK_PRESIDENT', 'PRO');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_POLICY',3,'BM','BANK_MANAGER', 'BP');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_POLICY',2,'BS','BANK_SUPERVISOR', 'BM');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_POLICY',1,'BT','BANK_TELLER', 'BS');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_POLICY',6,'HA','HOSPITAL_ADMINISTRATOR', 'PRO');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_POLICY',7,'HM','HOSPITAL_MANAGER', 'HA');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_POLICY',8,'DO','DOCTOR', 'HM');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_POLICY',9,'NU','NURSE', 'DO');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_POLICY',10,'CH','CHIEF', 'PRO');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_POLICY',11,'SE','SERGEANT', 'CH');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_POLICY',12,'PO','POLICE', 'SE');

EXECUTE SA_USER_ADMIN.SET_USER_PRIVS('OLS_POLICY','DB_ADMIN','FULL');
EXECUTE SA_USER_ADMIN.SET_USER_PRIVS('OLS_POLICY','POLICY_ADMIN','FULL,PROFILE_ACCESS');


SELECT * FROM ALL_SA_LEVELS;
SELECT * FROM ALL_SA_COMPARTMENTS;
SELECT * FROM ALL_SA_GROUPS;

select * from DB_ADMIN.BANK_RECORDS;

BEGIN
   SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('BANK_READ_POLICY','DB_ADMIN','BANK_RECORDS');
--   SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
--     POLICY_NAME => 'BANK_POLICY',
--     SCHEMA_NAME => 'DB_ADMIN',
--     TABLE_NAME  => 'BANK_RECORDS',
--     TABLE_OPTIONS => 'NO_CONTROL',
--     LABEL_FUNCTION => 'DB_ADMIN.get_bank_label(:new.IDENTITY_CARD_ID,:new.HANDLING)',
--     PREDICATE => NULL);
END;

UPDATE DB_ADMIN.BANK_RECORDS SET HANDLING='BP' where HANDLING='BP';
UPDATE DB_ADMIN.BANK_RECORDS SET HANDLING='BM' where HANDLING='BM';
UPDATE DB_ADMIN.BANK_RECORDS SET HANDLING='BS' where HANDLING='BS';
UPDATE DB_ADMIN.BANK_RECORDS SET HANDLING='BT' where HANDLING='BT';
COMMIT;

col BANK_READ_LABEL format a15
SELECT NAME, HANDLING, label_to_char(BANK_READ_LABEL) AS BANK_READ_LABEL FROM DB_ADMIN.BANK_RECORDS;

BEGIN
   SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('OLS_POLICY','DB_ADMIN','BANK_RECORDS');
   SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
     POLICY_NAME => 'OLS_POLICY',
     SCHEMA_NAME => 'DB_ADMIN',
     TABLE_NAME  => 'BANK_RECORDS',
     TABLE_OPTIONS => 'READ_CONTROL, WRITE_CONTROL',
     LABEL_FUNCTION => 'DB_ADMIN.get_bank_label(:new.IDENTITY_CARD_ID,:new.HANDLING)',
     PREDICATE => NULL);
END;

BEGIN
   SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('OLS_POLICY','DB_ADMIN','HOSPITAL');
END;

BEGIN
   SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('OLS_POLICY','DB_ADMIN','HOSPITAL');
   SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
     POLICY_NAME => 'OLS_POLICY',
     SCHEMA_NAME => 'DB_ADMIN',
     TABLE_NAME  => 'HOSPITAL',
     TABLE_OPTIONS => 'READ_CONTROL, WRITE_CONTROL',
     LABEL_FUNCTION => 'DB_ADMIN.get_hospital_label(:new.IDENTITY_CARD_ID,:new.HANDLING)',
     PREDICATE => NULL);
END;

--policy name, user name, max_read_label, max write label, min write label, def label, row label
EXECUTE SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY','BANK_PRESIDENT1','HS:BK,PO,HP:BP', 'HS:BK,PO:BP', 'HS');
EXECUTE SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY','BANK_MANAGER1','S:BK,HP:BM', 'S:BK,HP:BM', 'S');
EXECUTE SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY','BANK_SUPERVISOR1','C:BK:BS', 'C:BK:BS', 'C');
EXECUTE SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY','BANK_TELLER1','U:BK:BT', 'U:BK:BT', 'U');
EXECUTE SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY','BANK_PRESIDENT_NO_COMPARTMENT','HS:HP,BK:BP', 'HS:HP:BP', 'HS');
EXECUTE SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY','BANK_MANAGER_LOW_GROUP','S:BK,HP:BT', 'S:BK,HP:BT', 'S');
EXECUTE SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY','PROSECUTOR', 'HS:BK,PO,HP:PRO', 'HS:BK,PO,HP:PRO', 'HS');
EXECUTE SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY','DOC1', 'C:HP:DO', 'C:HP:DO', 'C');



SELECT * FROM DBA_SA_POLICIES ORDER BY policy_name;
SELECT * FROM DBA_SA_LABELS ORDER BY policy_name, label_tag;
SELECT * FROM DBA_SA_USERS ORDER BY policy_name, user_name;
SELECT * FROM DBA_SA_PROG_PRIVS ORDER BY policy_name, schema_name, program_name;
SELECT * FROM DBA_SA_SCHEMA_POLICIEs ORDER BY policy_name, schema_name;
SELECT * FROM DBA_SA_TABLE_POLICIES ORDER BY policy_name, schema_name, table_name;

